application: hbtpybest
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: greetings.app

libraries:                                                                      
- name: jinja2                                                                  
  version: latest                                                               
- name: markupsafe                                                              
  version: latest
